services:
  postgres:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgresql/data_new:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - ${POSTGRES_NETWORKS}

  redis:
    image: redislabs/redismod:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - ${REDIS_PORT}
    networks:
      - ${REDIS_NETWORKS}
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - ddd1-network

networks:
  ddd1-network:
    driver: bridge
