services:
  postgres:
    image: postgres:15
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - ./postgresql/data_new:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    networks:
      - ${POSTGRES_NETWORKS}

  redis:
    image: redislabs/redismod:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - ${REDIS_PORT}
    networks:
      - ${REDIS_NETWORKS}
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: ${PROMETHEUS_CONTAINER_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - ddd1-network
  grafana:
    image: grafana/grafana
    container_name: ${GRAFANA_CONTAINER_NAME}
    hostname: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug altermanager:debug ngalert:debug
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - ddd1-network
  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${NODE_EXPORTER_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^(sys|proc|dev|host|etc)($$|/)
    ports:
      - "9100:9100"
    networks:
      - ddd1-network
  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    container_name: ${POSTGRES_EXPORTER_CONTAINER_NAME}
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - ddd1-network
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: ${REDIS_EXPORTER_CONTAINER_NAME}
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    networks:
      - ${REDIS_NETWORKS}
    depends_on:
      - redis
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: elasticsearch-container
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elk/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - ddd1-network
  logstash:
    image: logstash:8.11.0
    container_name: logstash-container
    volumes:
      - ./elk/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk/pipeline:/usr/share/logstash/pipeline
    ports:
        - "5044:5044"
        - "5000:5000/tcp"
        - "5000:5000/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - ddd1-network
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:8.11.0
    container_name: kibana-container
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - ddd1-network
    depends_on:
      - elasticsearch
networks:
  ddd1-network:
    driver: bridge
